name: log_controller
version: 0.0.1-pre+3
description: A polymer element which lets you control the global logging configuration.
dependencies:
    logging: ">=0.9.2"
    polymer: ">=0.12.0 <0.16.0"
    core_elements: ">=0.0.6 <0.4.0"
transformers:
- polymer:
    entry_points: example/index.html
