name: log_controller
version: 0.0.1-pre+2
description: A polymer element which lets you control the global logging configuration.
dependencies:
    logging: ">=0.9.2"
    polymer: ">=0.12.0 <0.14.0"
    core_elements: ">=0.0.6 <0.3.0"
transformers:
- polymer:
    entry_points: example/index.html
