name: log_controller
description: A polymer element which lets you control the global logging configuration.
dependencies:
    polymer: "0.12.0-dev"
    core_elements: "<=0.0.6"
transformers:
- polymer:
    entry_points: example/index.html
